
artifacts_root: 'artifacts'

data_ingestion:
  data_root_dir: 'artifacts/data_ingestion'
  data_source: 'https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip'
  data_local_data_file: 'artifacts/data_ingestion/data.zip'
  data_unzip_dir: 'artifacts/data_ingestion/'
  data_source_type: 'csv'
  data_source_separator: ','

data_validation:
  data_root_dir: 'artifacts/data_validation'
  data_unzip_dir: 'artifacts/data_ingestion/winequality-red.csv'
  STATUS_FILE: 'artifacts/data_validation/status.txt'

data_transformation:
  data_root_dir: 'artifacts/data_transformation'
  data_unzip_dir: 'artifacts/data_ingestion/winequality-red.csv'
  data_preprocessed_file: 'artifacts/data_transformation/data.csv'
  data_preprocessed_train_file: 'artifacts/data_transformation/train.csv'
  data_preprocessed_test_file: 'artifacts/data_transformation/test.csv'
  data_source_train_test_split: 0.2
  data_source_random_state: 42

model_trainer:
  data_root_dir: 'artifacts/model_trainer'
  data_train_file: 'artifacts/data_transformation/train.csv'
  data_test_file: 'artifacts/data_transformation/test.csv'
  model_name: 'model'

